services:
  concourse-web:
    image: concourse/concourse:7.12
    command: web
    depends_on:
      - concourse-db
    ports:
      - 8080:8080
    volumes:
      - ./keys/web:/concourse-keys
    environment:
      CONCOURSE_EXTERNAL_URL: http://localhost:8080
      CONCOURSE_POSTGRES_HOST: concourse-db
      CONCOURSE_POSTGRES_USER: concourse_user
      CONCOURSE_POSTGRES_PASSWORD: concourse_pass
      CONCOURSE_POSTGRES_DATABASE: concourse
      CONCOURSE_ADD_LOCAL_USER: test:test
      CONCOURSE_MAIN_TEAM_LOCAL_USER: test
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: unless-stopped

  concourse-worker:
    image: concourse/concourse:7.12
    command: worker
    privileged: true
    cgroup: host
    depends_on: 
      - concourse-web
    volumes:
      - ./keys/worker:/concourse-keys
    stop_signal: SIGUSR2
    environment:
      CONCOURSE_TSA_HOST: concourse-web:2222
      # enable DNS proxy to support Docker's 127.x.x.x DNS server
      CONCOURSE_GARDEN_DNS_PROXY_ENABLE: "true"
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    restart: unless-stopped

  concourse-db:
    image: postgres:17.2
    environment:
      POSTGRES_DB: concourse
      POSTGRES_PASSWORD: concourse_pass
      POSTGRES_USER: concourse_user
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - concourse-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  concourse-db-data: